### ISSUE TITLE
Two minor differences between the code and paper for the ENR/ISTA experiments

### ISSUE THREAD

**Issue by bamos** [cvxgrp/nonexp_global_aa1#1]
Edit: These aren't differences and my original mistake was from accidentally using the Frobenius norm instead of the 2-norm for L

<details>
Just quickly noting this here in case anybody else runs into these issues, as I wasn't able to reproduce the results without these:

1. The paper uses an update with a step size of alpha and thresholding parameter of alpha*mu (just before eq 25), but the code uses alpha for both:
https://github.com/cvxgrp/nonexp_global_aa1/blob/3a1751e980164dcfd0b7108fc3255511f4d0f85a/codes/algorithms/fx.m#L57

2. The paper just above Fig 7 says:
![image](https://user-images.githubusercontent.com/707462/98043879-fcc59e00-1df3-11eb-8e36-a0068a9f1ced.png)
but the code sets this with the max eigenval: https://github.com/cvxgrp/nonexp_global_aa1/blob/3a1751e980164dcfd0b7108fc3255511f4d0f85a/codes/consoles/ISTA_enr.m#L16
</details>

**Comment by junziz** [comment]
Thanks a lot for carefully checking these! Please see my responses and explanations below.
1. For the first issue, I checked the original code and I think it is indeed consistent with the update formula before eq 25 (applied to the problem in eq 37). In particular, since the objective is 
``
F_1(x)+F_2(x),
`` 
where 
``
F_1(x)=\dfrac{1}{2}\|Ax-b\|_2^2+\dfrac{\mu}{4}\|x\|_2^2,  
`` 
and 
``
F_2(x)=\dfrac{\mu}{2}\|x\|_1,
``
we have that the gradient of $F\_1$ is 
``
\nabla F_1(x)=A^T(Ax-b)+\dfrac{\mu}{2}x,
`` 
and hence the entire update formula before eq 25 becomes 
``
x^{k+1}=S_{\alpha\mu/2}(x^k-\alpha*A^TAx^k+\alpha*A^Tb-\alpha*\dfrac{\mu}{2}x^k).
`` 
This should be consistent with:
https://github.com/cvxgrp/nonexp_global_aa1/blob/3a1751e980164dcfd0b7108fc3255511f4d0f85a/codes/algorithms/fx.m#L64
and 
https://github.com/cvxgrp/nonexp_global_aa1/blob/3a1751e980164dcfd0b7108fc3255511f4d0f85a/codes/algorithms/fx.m#L65
Please let me know if I misunderstood anything you mentioned, or if there is anything unclear in my above explanations! Thanks!
2. For the second issue, since $A^TA$ is symmetric and positive semi-definite, its 2-norm, largest singular value and largest eigenvalue are all equal. This can be seen by noticing that if A has an SVD as $A=UDV^T$, then $A^TA=VD^2V^T$, and since $D^2$ is diagonal and nonnegative, $VD^2V^T$ is both an SVD of $A^TA$ and an eigenvalue decomposition of $A^TA$. Hence max eigenvalue of $A^TA$ and 2-norm of $A^TA$ are both equal to the $\max(diag(D^2))$. Please feel free correct me if you find any mistakes in my reasoning here. Thanks!

Thanks again!

**Comment by bamos** [comment]
Thanks for the clarifications and quick response! Indeed you are right and I mis-read your code in the first one, and you are also correct for the second --- I now realize that the mistake in my re-implementation was that I was accidentally using the Frobenius norm instead of the 2-norm for this computation, making L an order of magnitude too large.

**Comment by junziz** [comment]
My pleasure!
